/*
 * ============================================================
 *  YOUR MEAL LIST  —  this is the only file you need to edit
 * ============================================================
 *
 *  Each meal is one block between the { } braces. Copy an
 *  existing block, paste it, and change the words in quotes to
 *  add your own. Keep the commas exactly where they are.
 *
 *  What each line means:
 *    name         the meal name, e.g. "Meatballs"
 *    category     "Lunch" or "Dinner"
 *    location     "Home" (cooked in) OR "Takeaway"/"Eating Out" (a treat)
 *    ease         "Easy", "Medium" or "Hard" (just a label)
 *    sides        the side dishes it CAN have, in [ ] and quotes
 *    min / max    how many sides to pick (e.g. min 2 max 4)
 *    days         which days it is allowed on
 *                 use: mon tue wed thurs fri sat sun
 *    ingredients  what goes on the shopping list for it
 *
 *  After editing: save the file, commit & push (or drag the
 *  folder to Netlify again) and the site updates.
 */

const MEALS = [
  {
    name: "Meatballs",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["mash", "gravy", "peas", "sweetcorn", "carrots", "wedges"],
    min: 2, max: 4,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["meatballs"],
  },
  {
    name: "Duck and pancakes",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["cucumber", "spring onion"],
    min: 2, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["duck and pancakes kit"],
  },
  {
    name: "Chinese style curry",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["prawn crackers", "boiled rice"],
    min: 2, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["chicken", "curry sauce"],
  },
  {
    name: "Pulled pork burgers",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["chips", "salad", "wedges", "sweet potato fries", "onion rings"],
    min: 1, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["pulled pork", "burger buns"],
  },
  {
    name: "Chicken burgers",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["chips", "salad", "wedges", "sweet potato fries", "onion rings"],
    min: 1, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["chicken burgers", "burger buns"],
  },
  {
    name: "Lasagna",
    category: "Dinner",
    location: "Home",
    ease: "Hard",
    sides: ["chips", "salad", "garlic bread"],
    min: 1, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["lasagna sheets", "tomato sauce", "minced beef", "white sauce"],
  },
  {
    name: "Chicken burger tacos",
    category: "Dinner",
    location: "Home",
    ease: "Hard",
    sides: ["fries", "salad", "onion rings"],
    min: 0, max: 1,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["mini tortillas", "minced chicken", "lettuce", "gherkins", "burger sauce"],
  },
  {
    name: "Mac & cheese",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["chips", "salad", "garlic bread", "wedges"],
    min: 0, max: 1,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["macaroni pasta", "milk", "cheese sauce"],
  },
  {
    name: "Sausages",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["beans", "chips", "wedges"],
    min: 2, max: 2,
    days: ["mon", "tue", "wed", "thurs", "sun"],
    ingredients: ["sausages"],
  },
  {
    name: "Beef ragu pappardelle",
    category: "Dinner",
    location: "Home",
    ease: "Hard",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: ["stewing steak", "pappardelle", "tomato sauce"],
  },
  {
    name: "Roast chicken",
    category: "Dinner",
    location: "Home",
    ease: "Hard",
    sides: ["peas", "sweetcorn", "carrots", "yorkies", "stuffing", "gravy", "cauliflower cheese"],
    min: 4, max: 6,
    days: ["sun"],
    ingredients: ["chicken breast"],
  },
  {
    name: "German Donner Kebab",
    category: "Dinner",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Nandos",
    category: "Dinner",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Chinese",
    category: "Dinner",
    location: "Takeaway",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Popeyes",
    category: "Dinner",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Wetherspoons",
    category: "Dinner",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "KFC",
    category: "Dinner",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Chippy",
    category: "Dinner",
    location: "Takeaway",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "McDonalds",
    category: "Dinner",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Southern style chicken",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["chips", "salad", "wedges", "sweet potato fries", "onion rings", "mash", "beans", "sweetcorn"],
    min: 2, max: 3,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Chicken fajitas",
    category: "Dinner",
    location: "Home",
    ease: "Hard",
    sides: ["salsa", "sour cream", "cheese", "tortilla chips"],
    min: 2, max: 3,
    days: ["fri"],
    ingredients: ["taco kit", "chicken"],
  },
  {
    name: "Fish & chips",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["mushy peas"],
    min: 1, max: 1,
    days: ["thurs", "fri", "sat"],
    ingredients: ["fish", "chips"],
  },
  {
    name: "Jacket potato",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["beans", "cheese", "tuna"],
    min: 2, max: 2,
    days: ["mon", "tue", "wed"],
    ingredients: ["jacket potatoes"],
  },
  {
    name: "Burger King",
    category: "Dinner",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Fish burgers",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["mushy peas", "beans", "wedges", "fries", "peas"],
    min: 1, max: 3,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["fish burger paties"],
  },
  {
    name: "Fry up",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: [],
    min: 0, max: 0,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["sausages", "bacon", "hash browns", "egg", "mushrooms"],
  },
  {
    name: "Noodle bowl",
    category: "Lunch",
    location: "Home",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["mon", "tue", "wed", "thurs", "fri"],
    ingredients: ["noodle bowl"],
  },
  {
    name: "Paninis",
    category: "Lunch",
    location: "Home",
    ease: "Easy",
    sides: ["ham filling", "chicken filling"],
    min: 1, max: 1,
    days: ["mon", "tue", "wed", "thurs", "fri"],
    ingredients: ["paninis"],
  },
  {
    name: "Cheese toastie",
    category: "Lunch",
    location: "Home",
    ease: "Easy",
    sides: ["ham filling", "chicken filling", "tomato"],
    min: 1, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["bread", "cheese"],
  },
  {
    name: "Greggs",
    category: "Lunch",
    location: "Eating Out",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Instant noodles",
    category: "Lunch",
    location: "Home",
    ease: "Easy",
    sides: ["egg"],
    min: 0, max: 1,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Pizza",
    category: "Dinner",
    location: "Home",
    ease: "Hard",
    sides: ["rocket", "parma ham", "pepperoni"],
    min: 0, max: 0,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["pizza dough", "mozzarella", "plum tomatoes", "garlic", "salt", "pepper"],
  },
  {
    name: "Turkey dinosaurs",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["mash", "gravy", "peas", "sweetcorn"],
    min: 2, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["turkey dinosaurs"],
  },
  {
    name: "Kebab burgers",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["chips", "salad", "wedges", "sweet potato fries", "onion rings"],
    min: 0, max: 0,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["burger buns", "kebab meat", "tortilla chips"],
  },
  {
    name: "Dominos",
    category: "Dinner",
    location: "Takeaway",
    ease: "Easy",
    sides: [],
    min: 0, max: 0,
    days: ["fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Sausage pasta",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["garlic bread", "salad"],
    min: 1, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Beans on toast",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["cheese"],
    min: 0, max: 1,
    days: ["mon", "tue", "wed"],
    ingredients: ["toast", "beans"],
  },
  {
    name: "Chicken mayo sandwich",
    category: "Lunch",
    location: "Home",
    ease: "Medium",
    sides: [],
    min: 0, max: 0,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["bread", "chicken", "mayo"],
  },
  {
    name: "Sausage rolls",
    category: "Lunch",
    location: "Home",
    ease: "Easy",
    sides: ["beans"],
    min: 0, max: 1,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["frozen sausage rolls"],
  },
  {
    name: "Carbonara",
    category: "Dinner",
    location: "Home",
    ease: "Hard",
    sides: [],
    min: 0, max: 0,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["egg", "spaghetti", "parmesan", "pecorino", "pancetta"],
  },
  {
    name: "Pie night",
    category: "Dinner",
    location: "Takeaway",
    ease: "Hard",
    sides: [],
    min: 0, max: 0,
    days: ["fri"],
    ingredients: [],
  },
  {
    name: "Southern fried chicken strips",
    category: "Dinner",
    location: "Home",
    ease: "Easy",
    sides: ["chips", "salad", "wedges", "sweet potato fries", "onion rings"],
    min: 1, max: 3,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: [],
  },
  {
    name: "Tacos",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["mexican rice", "chips"],
    min: 1, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["minced beef", "chicken", "hard shell tacos", "tortillas", "tomato", "lettuce", "cheese", "sour cream", "guacamole", "salsa"],
  },
  {
    name: "Indian curry",
    category: "Dinner",
    location: "Home",
    ease: "Medium",
    sides: ["naan bread", "popadoms"],
    min: 1, max: 2,
    days: ["mon", "tue", "wed", "thurs", "fri", "sat", "sun"],
    ingredients: ["Curry sauce", "microwave rice"],
  },
];
